project:
  type: website
 
website:
  title: "DNA-Geek's Playground"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://dnageek.github.com/
      - icon: linkedin
        href: https://www.linkedin.com/in/jie-wu-8592526/
format:
  html:
    theme:
        light: flatly
        dark: darkly
    css: styles.css
    include-in-header: _includes/google-analytics.html


